<?php


namespace App\Http\Requests\SMS;


use App\Models\SMS\WeeklyReports;
use App\Rules\MustBeSunday;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;


class WeeklyReportFormRequest extends FormRequest
{
    public function rules(){
        $week_ending = $this->week_ending;
        $crop_year = $this->crop_year;
        $mill_code = Auth::user()->mill_code;
        return [
//          'crop_year' => 'required|string',
//          'week_ending' => [
//              'required',
//              'date_format:Y-m-d',
//              Rule::unique('weekly_reports')->where(function ($query) use ($week_ending,$crop_year){
//                  return $query->where('week_ending' ,'=',$week_ending)
//                      ->where('mill_code' ,'=',Auth::user()->mill_code)
//                      ->where('crop_year','=',$crop_year);
//              }),
//              new MustBeSunday(),
//          ],
//          'report_no' => [
//              'required',
//              'string',
//              Rule::unique('weekly_reports')->where(function ($query) use ($week_ending,$crop_year){
//                  return $query
//                      ->where('mill_code' ,'=',Auth::user()->mill_code)
//                      ->where('crop_year','=',$crop_year);
//              }),
//          ],
            'calendar_slug' => [
                'required',
                'string',
                Rule::unique('weekly_reports')->where(function ($query) use ($mill_code){
                  return $query->where('mill_code' ,'=',$mill_code);
                }),
            ],
            'dist_no' => 'required|string',
        ];
    }
    public function messages()
    {

        $href = '';
        $report = WeeklyReports::query()->where('week_ending','=',$this->week_ending)->first();
        if(!empty($report)){
            $href = route('dashboard.weekly_report.edit',$report->slug);
        }

        return [
            'week_ending.unique' => 'You have already made a report for this week ending. <a href="'.$href.'" target="">Click here to edit</a>.',
            'calendar_slug.unique' => 'You already have an existing report for this week ending.',
        ];
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}